spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 1000s
  cache:
    redis:
      key-prefix: redis-cache
      default-expiration: 60
    type: redis

  security:
    user:
      name: admin
      password: 123
server:
  port: 8083
